apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bolnica-ingress
  namespace: bolnica-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: bolnica.dev.ibis.com
      http:
        paths:
          - path: /front
            pathType: Prefix
            backend: 
              service:
                name: front
                port: 
                  number: 80

    # - host: bolnica.dev.ibis.com
    #   http:
    #     paths:
    #       - path: /front
    #         pathType: Prefix
    #         backend: 
    #           service:
    #             name: front
    #             port: 
    #               number: 80
    # - host: bolnica.dev.ibis.com
    #   http:
    #     paths:
    #       - path: /front
    #         pathType: Prefix
    #         backend: 
    #           service:
    #             name: front
    #             port: 
    #               number: 80