apiVersion: apps/v1
kind: Deployment
metadata:
  name: bolnica-laboratory
  labels:
    app: bolnica-laboratory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bolnica-laboratory
  template:
    metadata:
      labels:
        app: bolnica-laboratory
    spec:
      containers:
      - name: bolnica-laboratory
        imagePullPolicy: Always
        image: ghcr.io/raf-si-2021/bolnica-laboratory-service:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        env: # napraviti env vaijable da bi mogli da lepo koristimo servise
          - name: "spring.datasource.url"
            value: "jdbc:mysql:replication://mysql-0.mysql:3306,mysql-read:3306/user?serverTimezone=UTC"
          - name: "spring.datasource.username"
            value: root
          # - name: "spring.datasource.password"
          #   valueFrom: 
          #       secretKeyRef: 
          #         name: bolnica-secret
          #         key: mysql-root-password
          #         optional: false
          - name: "spring.jpa.generate-ddl"
            value: "true"
          - name: "spring.jpa.hibernate.ddl-auto"
            value: "update"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: bolnica-laboratory
spec:
  selector:
    app: bolnica-laboratory
  ports: 
    - protocol: TCP
      port: 8083
      targetPort: 8083

# u ingresu servicePort i u servisu port treba da se poklapaju