apiVersion: apps/v1
kind: Deployment
metadata:
  name: bolnica-user
  labels:
    app: bolnica-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bolnica-user
  template:
    metadata:
      labels:
        app: bolnica-user
    spec:
      containers:
      - name: bolnica-user
        imagePullPolicy: Always
        image: ghcr.io/raf-si-2021/bolnica-user-service:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        env: 
          - name: "spring.datasource.url"
            value: "jdbc:mysql://user-db:3306/user?serverTimezone=UTC"
          - name: "spring.datasource.username"
            value: root
          - name: "spring.datasource.password"
            valueFrom: 
                secretKeyRef: 
                  name: bolnica-secret
                  key: mysql-root-password
                  optional: false
          - name: "spring.jpa.generate-ddl"
            value: "true"
          - name: "spring.jpa.hibernate.ddl-auto"
            value: "update"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bolnica-user
spec:
  selector:
    app: bolnica-user
  ports: 
    - protocol: TCP
      port: 8081
      targetPort: 8081
